apiVersion: apps/v1
kind: Deployment
metadata:
  name: pintu-app-deployment
spec:
  selector:
    matchLabels:
      app: pintu-app
  template:
    metadata:
      labels:
        app: pintu-app
    spec:
      containers:
      - name: pintu-app-container
        image: 14022021/web-application:latest
        ports:
        - containerPort: 8080